<?xml version="1.0" encoding="utf-8"?>
<!-- Date(ymd)/time(hms) 2026/09/21 19:01:16 -->
<Xpl-source>
<HostEnvironment>
<Config>
<FileId>0x0c667a71</FileId>
<Target>Robox Motion Control</Target>
<XplType>RoboticProgramLanguage</XplType>
</Config>
</HostEnvironment>
<XplEnvironment>
<Info>
<Title LcId="1033">
<![CDATA[XPL program]]>
</Title>
<Description LcId="1033">
<![CDATA[XPL program edited from teachgun]]>
</Description>
<Version>1.0.0</Version>
<Author>Robox SpA</Author>
</Info>
<Pous>
<Pou>
<Name>Main</Name>
<Type>Program</Type>
</Pou>
</Pous>
</XplEnvironment>
</Xpl-source>